export { default as Form } from './Form'
export { default as HeadCard } from './HeadCard'
export { default as MultipleChoice } from './MultipleChoice'
export { default as NameInput } from './NameInput'
export { default as ShortText } from './ShortText'
export { default as Submit } from './Submit'
export { default as Letter } from './Letter'
export { default as AboutMe} from './AboutMe'
export { default as MusicPlayer} from './MusicPlayer'
export { default as Thanks} from './Thanks'
export { default as Theme} from './Theme'
export { default as ThemeButton} from './ThemeButton'
export { default as WarnBeforeUnload} from './WarnBeforeUnload'